import React from 'react'

import solarHouse from '../../solar house.webp'
import './science.css'

function Science(){
    return (
        <div className='science-component'>
            <div className='science-steps-section'>
                <p>How Solar Power Systems Work</p>
                <p id='science-subtitle'>Shining The Light On Solar</p>
                <p>Since our caveman days, we humans have been burning things like wood and coal to provide the power we need to “keep the lights on”, so to speak. This whole time the ultimate power generator was literally hanging just above our heads.</p>
                <p>Today, solar power systems are leading us into a cleaner and more renewable future. Solar panels convert the free and abundant energy of the sun into electricity that can keep refrigerators humming, air conditioners chilling, washing machines whirling, and homes alive with power.</p>
                <div className='science-steps'>
                    <p>The graphic below gives you a basic idea of how solar power systems work:</p>
                    <div className='science-align-top-steps'>
                        <div id='top-steps-left'>
                            <nav>
                                <p id='science-step-subtitles'>1. Solar Panels</p>
                                <p>Turn sunlight into direct current (DC) electricity.</p>
                            </nav>
                            <nav>
                                <p id='science-step-subtitles'>2. Bi-directional Meter</p>
                                <p>The bi-directional meter tracks the amount of electricity (kWh) produced, consumed and sent to the grid by your home. It spins backwards when solar generation exceeds home consumption, sending energy back to the utility grid for full credit at the retail rate.</p>
                            </nav>
                            <nav>
                                <p id='science-step-subtitles'>3. Performance Monitor</p>
                                <p>The performance monitoring system measures and monitors all energy generated by solar electric system and provides alerts about system performance.</p>
                            </nav>
                        </div>
                        <img src={solarHouse} alt='Solar-House-Steps' />
                    </div>
                    <div className='science-align-bottom-steps'>
                        <nav>
                            <p id='science-step-subtitles'>4. AC Disconnect</p>
                            <p>AC disconnect is a manual safety switch that can be used to separate the home’s electrical system from the solar electricity system if necessary.</p>
                        </nav>
                        <nav>
                            <p id='science-step-subtitles'>5. Utility Power</p>
                            <p>Utility power is still automatically provided from the grid at night or during days when your demand exceeds your solar energy production.</p>
                        </nav>
                        <nav>
                            <p id='science-step-subtitles'>6. Inverter</p>
                            <p>The inverter converts solar-generated DC electricity into alternating current (AC) electricity, the form of energy used by most standard household appliances. If your system utilizes mico-inverters, they are located on the roof, under the panels and may not be visible.</p>
                        </nav>
                    </div>
                </div>
            </div>
            <hr></hr>
            <div>
                <p id='science-subtitle'>Sun Science | A Deeper Look Into Solar Power For The Home</p>
                <p>Want to dig a little deeper into how solar energy works? Excellent! We think science is cool too, especially when it results in a lower utility bill at the end of the month. Let’s start with a question.</p>
                <p>What happens if you leave a handful of crayons outside on a sunny day in July? An hour later, you’ll have some colorful puddles of wax to clean up. As with most materials, the energy of the sun turns into heat. This heat causes the electrons inside the crayons to get excited and do a little dance in place. This movement is what turns your solid coloring tool into a useless puddle.</p>
                <p>In certain specific materials, the energy of the sun causes the electrons in the material’s atoms to actually “jump”, creating an electrical current, which can be harnessed. This type of material is used to create a photovoltaic cell (photo = light and voltaic = voltage). One of the most popular materials used to make photovoltaic cells is crystalline silicon. This is what the majority of solar panels are made of.</p>
                <nav>
                    <p>Crystalline silicon is often used to generate solar power for the home due to its:</p>
                    <ul>
                        <li>High efficiency: Silicon can convert up to 22% of sunlight’s energy into electricity</li>
                        <li>Durability: Silicon solar panels can last up to 50 years</li>
                        <li>Minimal care required: Silicon panels are nearly self-sustaining</li>
                    </ul>
                </nav>
            </div>
            <hr></hr>
            <div>
                <p id='science-subtitle'>Your Energy Ecosystem</p>
                <p>When it comes to solar power for the home, placement is a big deal. Solar panels work best when they get as much uninterrupted sunlight as possible each day. In the United States, this means placing the panels as close to true south as possible and inclined at an angle close to the area’s latitude. The more sunlight, the more energy the panels can produce.</p>
                <p>What happens at night when the sun is gone but you still need energy to make dinner, watch your favorite show, and do a load of dishes? This is where the idea of the energy ecosystem comes in. Your solar panels are actually hooked to your home’s energy grid.</p>
                <p>During the day, your solar panels may produce more energy than you need, especially if the members of your household are at work or school. This energy doesn’t go to waste. Instead, it goes into the energy grid and your electricity meter actually turns backwards. Yes, it can do that.</p>
                <p>At night, when it’s time to turn on some lights, you’ll need to take energy out of the grid (since your panels can’t create energy in the dark). The idea is that the energy you take from the grid at night will roughly even out to the energy your solar panels fed into the grid during the day. Thus, the panels have actually provided you with most or all the energy you needed throughout the day. This is what we mean by an energy ecosystem.</p>
            </div>
            <hr></hr>
            <div>
                <p id='science-subtitle'>Direct Current into Alternating Current</p>
                <p>When the sun shines down upon a solar panel, the sun’s energy is turned into a direct current (DC). Unfortunately, the DC can’t just plug right into your home and start powering your microwave and other electronics. Your home’s electrical system speaks a different language called alternating current (AC). In order to actually enjoy the energy your solar panel array is producing, your system will use a device called an inverter to turn the DC coming from your solar panels to the AC that your home can use to feed your electricity needs.</p>
            </div>
        </div>
    )
}

export default Science